### ISSUE TITLE
Invitation interface v 0.2

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#162]
Relevant parts pulled out of #128 
___________
Prior url: http://submissions.capitalcityrecords.ca/invite
Future url: https://capitalcityrecords.ca/admin/invite

- [x] Send localmusic@epl.ca copies of sent invitations so we have a record of the unique links sent to each artist
- [x] "Reject" button sends Deferral email
- [x] cc epl on initial invitation emails (maybe other messages, too)

Text for the Deferral (Reject) email is on page 2 of this document: https://drive.google.com/open?id=17hdD3rlN3ZZkYGq2TEqqgspcXQcB995KF6tNTUYrAKc

I would also like to make all email copy no longer hard-coded so that non-devs can tweak copy if necessary.

This should be able to be mostly ported over directly from prior version, but will need some changes due to differences in internal Ember APIs.

**Comment by acecarruthers** [comment]
I've told the jury they have until January 7, 2016 to make their recommendations. If possible, I'd like to use this tool to send invitations out to artists on January 8.

**Comment by acecarruthers** [comment]
I just made a small revision to the text in the acceptance email https://drive.google.com/open?id=17hdD3rlN3ZZkYGq2TEqqgspcXQcB995KF6tNTUYrAKc. Since a number of local artists have submitted more than one album this time around, I think it we should specify which album has been accepted in the letter. I marked this with an underlined blank space in the text.

**Comment by mbrakken** [comment]
I'll take a look. FYI, I'm planning to set this up so you'll be able to
edit that email text yourself in the future. At least initially that'll
happen directly in Github. I'll show that to you when it's out.

**Comment by acecarruthers** [comment]
Hi @mbrakken, This works great! Thanks! Just a few points:
- I am still wondering if it is possible to add in the specific name of the album that has been accepted, just so that people who submitted multiple albums don't get confused about which has been accepted and which hasn't. Details are in the Google Doc linked above.   
- [ ] The link in the invitation email sent me right to the license page in all cases. Is it possible for it to go to the Artist information page? 
- [ ] Can you please change the email subject of the deferral email to "Capital City Records Submission"

Thanks!

**Comment by mbrakken** [comment]
Updates are out, @acecarruthers. I'll let you close this once you've reviewed.

**Comment by acecarruthers** [comment]
Thanks @mbrakken The only thing is that the album name isn't appearing in the invitation email. I don't know how to add that myself. I accidentally didn't put a check box beside it. Is that still possible?

**Comment by mbrakken** [comment]
Totally. I'll take a look.

**Comment by mbrakken** [comment]
About to deploy this update.

**Comment by acecarruthers** [comment]
@mbrakken Thanks! This is working great!
