### ISSUE TITLE
Download buttons and Login not functioning

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#183]
I've tested this on a few albums (listed below) and I think it is across all albums. The download buttons and login button aren't doing anything. The popup requesting the user's library card and PIN is not appearing. 

https://capitalcityrecords.ca/albums/josh-sahunta-lights
https://capitalcityrecords.ca/albums/the-duettes-your-little-voice
https://capitalcityrecords.ca/albums/columbus-commonwealth

9:20am MT, Chrome & Firefox, Windows 7 Desktop, Dec 17
4:00pm MT, Firefox, Windows 7 Lenovo laptop, Dec 16

**Comment by mbrakken** [comment]
Fixed.

Note to self: I think it's time for automated tests...

**Comment by acecarruthers** [comment]
I just tried this again on Firefox and it is not working again. Chrome appears to be working fine. 

5:25pm MT, Firefox 42.0, Windows 7, Dec 17.

**Comment by acecarruthers** [comment]
Customer reported having the same trouble on multiple browsers

**Comment by mbrakken** [comment]
Hmm. I am able to sign in on Chrome and Firefox, both via the login link and as part of the download process.

I do noticed that the submit button has to be hit, rather than just hitting enter / return after entering PIN.

When you reopened this, were you not seeing the login form at all, or was the login form not responding? (Either in that nothing happened, or it closed but it didn't log you in?)

NB: I plan to make hitting enter / return submit the form, but I first want to make sure there aren't other issues first.

**Comment by acecarruthers** [comment]
The problem was that clicking "LOGIN" or any download button had no effect. The login form did not appear.
