### ISSUE TITLE
Duration data missing from 20/23 submissions

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#197]
There are 91 instances of  ```"duration": 0,``` in the submitted albums' data. I haven't listened to them all yet, but the ones I have listened to have uploaded just fine. (The number 91 includes the tracks from Choir and Marching Band which don't appear to have uploaded at all noted in #192). 

At least one track is missing duration data in the following artists' albums:
- Tyler Butler
- Rebecca Lappa
- Heaviside
- Max Uhlich
- Counterfeit Jeans
- Carrie Day
- Beth Portman
- Dirt Road Angels
- Endivera
- Red Ram
- Kevin Maimann
- Bong Sample
- The Olm/Ocra
- Consilience
- Switches
- Lindsey Walker
- Barry Campbell
- Amy Van Keeken
- Kathleen Yearwood
- The Rusty Aces

Perhaps this is tied to #172?

**Comment by kellyhiser** [comment]
also noted: track duration did not set for the following tracks during the submission process: 



https://capitalcityrecords.ca/admin/jury/rattle-rattle-set-traps-1447726568232

https://capitalcityrecords.ca/admin/jury/rebecca-lappa-tattered-rose-1447636730652

https://capitalcityrecords.ca/admin/jury/consilience-walking-through-a-dead-night-ep-1447641915420

https://capitalcityrecords.ca/admin/jury/endivera-shameless-1447688597828

**Comment by prestonaustin** [comment]
Note for @acecarruthers @kellyhiser - Not sure what has been communicated about known causes here, so for the record:

There are two things we know are causing this bug: a problem with committing bad data to MUSICat's metadata store so the API doesn't "know" durations, and an overlapping but distinct problem with JSFS not parsing some files properly and ending up with stored object with no duration header. There may be more, but I think that's it.

We are fixing both. The upcoming publishing update will add a feature to fix zero durations by looking at the JSFS headers for the audio, and setting the MUSICat metadata to match. This feature will be accessible to libarians, but not artists or other folks editing the submissions, as a "last stage" fix. 

The only reason MUSICat has metadata is so we can efficiently display and work with durations without looking at the media objects (track files) headers. The "canonical" source of duration information is the headers in the JSFS object store, which analyzes files and computes their properties when they get stored. Or at least, that's what we want it to do. Turns out there is also a bug, which we are now working on, that causes JSFS headers to lack duration information for some audio. SO...I'll be deploying a fix to MUSICat first that will allow the MUSICat publishing interface to repair cases not impacted by the JSFS bug, then we'll fix JSFS itself and re-compute missing headers, then we'll be able to use the MUSICat fix again to repair the remaining cases. 

Nobody else needs to do anything as a result of this, this note is just to avoid confusion later between the two bug fixes and the two sweeps through to repair all the cases. This also means I'll appear to be working out of priority order, but that's just because I need to get the publishing update out in order to get the duration fix update out, then turn my attention to assisting Marc and Jason on deploying the JSFS update and reprocessing all stored tracks with missing headers.

If this squeezes out all the known cases, we'll then want to watch for any new cases where files don't get durations in MUSICat, JSFS, or both. There should be none but the heterogeneity of audio files folks are uploading has made it more challenging than expected for us to get a fully open source approach to always parse them happily. The "happy path" that should always work, by the way, is WAV files ripped from a CD or a master copy compliant with CD sample rate and bit depth.

**Comment by kellyhiser** [comment]
MUSICat track duration tool in publishing is done. JSFS patch described above is in progress. One new thing: Preston is also going to change how upload works so all uploads are MMS processed on their way to JSFS which will fix several more classes of zero-duration problem (maybe all) and may also fix some won't-upload problems.

**Comment by acecarruthers** [comment]
@kellyhiser should I be able to/should I go ahead and update the durations in all the records now?

**Comment by kellyhiser** [comment]
@acecarruthers it would be good to do some testing of this if you haven't already. It likely won't work for some tracks. All of them will be fixed for the launch.

**Comment by acecarruthers** [comment]
When I tried testing the Update Track Durations button on Amy Van Keeken's _So Long_, nothing appeared to happen. Amy's tracks also appear not to be playing at all, so I am not going to test any more.

**Comment by kellyhiser** [comment]
@mbrakken fixed this with a magic button :)

**Comment by mbrakken** [comment]
Magic button + migration of data to new, better storage server

**Comment by mbrakken** [comment]
Data === files
