### ISSUE TITLE
All Artist banner images missing from review & publish page

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#214]
These are the first two that I noticed, but then, I checked most of them and all images appear broken: 

Rebecca Lappa:
https://capitalcityrecords.ca/admin/review-and-publish/submissions/artists/rebecca-lappa 
Link to the banner image from the data endpoint: 
https://ccrapi2.murfie.com/complete-submission/artists/rebecca-lappa/dsc_0453-edit.jpg
Error message says "the image X cannot be displayed because it contains errors"

F&M. Their banner is appearing live on the website. 
https://capitalcityrecords.ca/admin/review-and-publish/submissions/artists/f-and-m 
https://capitalcityrecords.ca/artists/f-and-m

**Comment by acecarruthers** [comment]
Update: Switches thumbnail is appearing on the Review and Publish page. 
https://capitalcityrecords.ca/admin/review-and-publish/submissions/artists/switches

**Comment by kellyhiser** [comment]
@acecarruthers we're looking at this. Looks like it's actually a bigger media delivery problem: streaming isn't working in admin or the public site. Preston's working on it now, and thinks he knows that the problem is with underlying JSFS. We'll keep you posted.

**Comment by kellyhiser** [comment]
@acecarruthers for now, please don't add or change any media.

**Comment by mbrakken** [comment]
We've resolved this for the time being. Server is back operating at
reasonable levels, and media is getting served out.

Among other things, I discovered that an old version of the file store that
I thought had been deprecated is still in use. I'm putting together a plan
to set up a new, fully up to date file storage and migrate media into it.

We may encounter some loss of access keys during this migration, which
would prevent artists from "materially" deleting previously-uploaded files,
but (1) we already have been meaning to duplicate files associated with
published records into public-ish namespaces, so that artists could not
arbitrarily delete them after signing licenses and (2) we will still be
able to update json representations so that deleted files will not be
trivially accessible in served to UIs. Since my leading priority is to
maintain integrity of files served to publicly-facing interfaces, I'm
willing to accept various short-term complications associated with the
larger goal.

Also, migrations will all be transparent to user-facing interfaces. Ideally
you should never know they happen until I tell you they've been done.

Best,
M
