### ISSUE TITLE
all albums in Review & Publish now marked with "( ! )"

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ccr-app#221]
note reads: The following fields have changed: tracks.

**Comment by kellyhiser** [comment]
this condition persists for new albums that I'm publishing right now (nighttime, 4/25)

**Comment by mbrakken** [comment]
Sounds like a race condition. I see different behavior as I reload multiple
times or come into the route differently. Likely similar to whatever is
behind weirdness relating to jury reviews not always appearing.

**Comment by mbrakken** [comment]
Ahh, I now know what this is (or have a strong assumption). I misread the issue originally and thought *everything* was marked as such.

Probably the comparison code on the tracks array needs to be updated, probably because of lookup of constructor functions I use in there.

That's some hacky code that could use a cleanup.

**Comment by kellyhiser** [comment]
moved to stem
