### ISSUE TITLE
Album link sometimes does not display on artist page

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#32]
The first time I looked at this page, the link to the album didn’t appear. The second time I looked at it, it did appear. This is not a problem because it doesn’t seem to happen again after the first time. I just thought I’d point it out in case it is a clue for fixing something else. 

http://ccr-public.herokuapp.com/artists/death-by-robot 

Also happened with: Felt Hat String Band, TOMBTHEMUSICIAN, Nature Of, Passburg, Paul Richey and the Fusionauts, the Duettes, The Velveteins, Tyler Butler, Wilfred N and the Grown Men

**Comment by mbrakken** [comment]
I haven't been able to reproduce this for some time. My leading hypothesis initially was that it was an artifact of memory issues, since it cropped up after a bunch of content had been added. Nothing since has changed that hypothesis.

If we can reproduce it, let's reopen with steps to reproduce. There's no clear vector for debug otherwise.
