### ISSUE TITLE
Logo issues on album page

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#34]
http://ccr-public.herokuapp.com/albums/marystown-a-perfect-reality
Weird dropped vimeo logo appeared beside the facebook logo and linked to band website. Refreshed the page and saw three of the them. Refreshed the page and they were all gone. Very strange.

**Comment by mbrakken** [comment]
Issue is with the url. That section is intended for social media urls, and i'm applying a class tag to the link to properly position the appropriate logo from a sprite.

Easy solution: remove url to artist's website from that section (in the review-and-publish interface), since it's the same url used in the Artist Webpage section

Alternatively, include a general fallback img for cases where we don't have something else to show.

**Comment by mbrakken** [comment]
it looks like the former easy solution just happened: http://ccr-public.herokuapp.com/artists/marystown

**Comment by prestonaustin** [comment]
Closing - unless @mbrakken wants it reopened.
