### ISSUE TITLE
Force SSL on heroku

### ISSUE THREAD

**Issue by nagapampa** [therabble/ccr-app#68]
Jason,

I was given 2 options for forcing https:// redirects: With your app, I'd recommend one of two things: either a) setup this redirect within your app so that any http requests that come in, redirect automatically to https, or b) use the Nginx buildpack and use that to perform the necessary redirect.

Let's discuss the best approach and how to implement.

**Comment by prestonaustin** [comment]
@jjg please contact Carie today to check in on this and offer a decision so she can move forward, or assign the ticket back to me if you don't know.

**Comment by jjg** [comment]
Hey @prestonaustin & @nagapampa,

I don't know anything off-hand about the options they present here, so I'd have to bump something else and dedicate some time to digging into it to say what's best (and how to do either :).  It might be faster to run this past @southpolesteve since he's more into Heroku products than I am.

**Comment by southpolesteve** [comment]
@nagapampa @prestonaustin I believe this is configurable in the heroku buildpack for ember CLI https://github.com/tonycoco/heroku-buildpack-ember-cli#force-httpsssl

**Comment by prestonaustin** [comment]
@nagapampa if you think Steve's suggestion will work, please self-assign
this ticket and try that, otherwise let me know you are blocked here and
need a better answer and I'll pick it up Tuesday.

**Comment by jjg** [comment]
DONE!

(pls test @prestonaustin )

**Comment by prestonaustin** [comment]
Worked. Pleez cloze :)
