### ISSUE TITLE
User cannot play tracks twice

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#74]
user feedback (modified to be more specific): If I’m half way through a song [My Ego by Lauren Busheikin] and decide that I want to re-listen to a song I already heard [Angela by Lauren Busheikin], it doesn’t work:  If I try to switch automatically to [Angela], [My Ego] keeps going.  If I try to stop the [My Ego] and then start [Angela], [My Ego] starts again."  

an update: since this user has listened to Lauren Busheikin's full album, she is not able to listen to any of the tracks again.
 
http://wax.capitalcityrecords.ca/albums/lauren-busheikin-we-love 

tester, Chrome, Windows 7, 16 July, between 8:30 and 9:30 am MT

**Comment by prestonaustin** [comment]
@jjg did you break this in your work this morning? This is new and impacting multiple people.

**Comment by jjg** [comment]
@prestonaustin afaik the files I migrated are not in use yet, and I didn't make any changes to the original source, so this should be working the same as it was yesterday, from a server perspective?

**Comment by jjg** [comment]
Just did a quick test with the album in question (to monitor the media file requests) and I was able to begin the first track, click to another track, play for awhile and jump back to re-start the first track (not sure if that's exactly what's being reported here?).  This worked as expected (Chromium on Linux).

Watching the requests, they appear to be hitting ccrjsfs confirming that the new copies are not in use yet, so I wouldn't expect the migration changes to be the root cause here.

**Comment by jjg** [comment]
@prestonaustin @mbrakken I did notice that it makes one request, cancels it and then makes a second; not sure if this is relevant but it seemed odd so I wanted to share it:

![multirequests](https://cloud.githubusercontent.com/assets/122858/8733075/33648ef0-2bc7-11e5-80e2-e6a2a1ce6adc.png)

**Comment by mbrakken** [comment]
@jjg I've noticed this, but I'm not sure what is causing it. Possibly something in soundmanager, or possibly an event is triggering twice (I'm pretty sure I tried debug logging to see if that was the case, and didn't notice a double trigger, though). It's been like that since before this player (tracks on the jury interface did the same).

**Comment by jjg** [comment]
That's cool @mbrakken, I didn't think it was directly related and it doesn't seem to impede playback, but thought I'd mention it.

**Comment by mbrakken** [comment]
@acecarruthers if the person fully refreshes the site, are they still unable to play?

**Comment by mbrakken** [comment]
Never mind. I'm reproducing. It's not on the streaming side. Debugging.

**Comment by mbrakken** [comment]
I haven't tested this, but I think it'll fix the problem: https://github.com/therabble/ccr-app/pull/75

**Comment by prestonaustin** [comment]
@nagapampa Please test and deploy (or deploy for @acecarruthers to test if you can't reproduce problem)

**Comment by mbrakken** [comment]
I have since tested it. Works as expected (I added that comment in the pr, not here).
