### ISSUE TITLE
Update image urls through mms

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#86]
MMS now (or soon? paging @jjg for clarification) supports specifying width and format. We'll want to update image urls accordingly.

Currently, MMS image urls are properties on a model ([album] (https://github.com/therabble/ccr-app/blob/master/app/models/album.js#L64), [artist] (https://github.com/therabble/ccr-app/blob/master/app/models/artist.js#L100), [poster] (https://github.com/therabble/ccr-app/blob/master/app/models/poster.js#L33)). I think it makes more sense to instead construct one or more helpers that take the base url and whatever other parameters make sense to construct the final src url.

We'll want to process all images, so be sure to update on the player component, individual album, artist, and poster interfaces, and list interfaces.

For artist thumbnails, we may also want to update treatment. Currently, artist thumbnails are displayed as background images, not as image tags (in order to give a more uniform appearance). Assess changes based on results.

**Comment by jjg** [comment]
Support for JPEG and scaling deployed, example here:

https://github.com/murfie/mms#transcode-large-jpeg-into-small-jpeg

Note that you can only specify the width (height is calculated to preserve aspect ratio).  This has been tested with JPEG input and ouput.

**Comment by prestonaustin** [comment]
Note that this can also now be used to call our "static" images, so if we
want to leave top resolution images (like the home page banners) in the
repo for things we don't have a publishing chain for, we can still call
those graphics via MMS (in theory) rather than creating multiple static
versions for CSS breakpoints. This is worth doing even when we are not
resizing or changing format of that source image - because the MMS caching
layer will be task optimized for this over time, and keeps media traffic
off the main app-serving node (currently Heroku).

I would not do this for small interface graphics at this time, or logos,
just the various "content" media objects.

**Comment by nagapampa** [comment]
@mbrakken was this implemented in that PR you created earlier this week?  I see poster images using this code:
mmsURL: ENV.MMS + '/tc?src=',
and album/artist images using mms.  What else needs to be completed on this?

**Comment by lahollen** [comment]
@acecarruthers since marc is out can you check this?

**Comment by acecarruthers** [comment]
@lahollen is there a chance you meant someone else? I wouldn't know how to check this.

**Comment by lahollen** [comment]
oops! sorry! i meant @nagapampa

**Comment by nagapampa** [comment]
Album, artist and poster are all using MMS.
