### ISSUE TITLE
SOCAN/SCI logging

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#9]
Presumably, this is logging plays/downloads. Should this come from the api or the client? What needs to be logged and where?

**Comment by mbrakken** [comment]
SOCAN/SCI info https://docs.google.com/file/d/0B56HcVGi1B3nVlp6dFZmOGNGeVE/edit

**Comment by prestonaustin** [comment]
- [ ] Log the minimum required information for SOCAN/SCI compliance per the URL above
- [ ] Need not deliver a document, OK to provide a link that allows log retrieval for appropriate reporting periods
- [ ] This does not need to be an API call, but if implemented as an API then also provide sample URLs or requests for client side, and create a separate task to build the client view

**Comment by jjg** [comment]
I started looking into the requirements for this and I'm not sure we can get the info needed by examining requests server-side (telling the difference between a stream and a download, or knowing if playback completed or not, etc.).  This is compounded by the fact that not all of these requests go through the same server components, etc.

At this point I'm leaning toward having an endpoint that the client logs these details to when the events happen client-side.  This would allow us to log activities more accurately as well as log the necessary details (since presumably the client knows things like the artist name, etc. when playing a track) without having to do post-processing of the logs, etc.

**Comment by prestonaustin** [comment]
@jjg I'm fine with building up a server side endpoint that the client calls to log plays and downloads, please spec and build the endpoint and let @nagapampa know what client actions should ping the logging endpoint by creating github tasks as you get logging endpoint responding.

**Comment by jjg** [comment]
Sounds good @prestonaustin.  I need to give the server-side a little thought first but I'll get the interface defined first so we can start logging requests and see what we have to work with.

**Comment by prestonaustin** [comment]
We need to confirm the data for this is being logged somewhere we won't lose it, ideally by Thursday morning. Then we can move finishing this out of the way of the beta, and get reporting in place by end of July. Actual reports are not a beta-done requirement, but tracking the data about plays and downloads is. @jjg let's discuss tomorrow how we can split this into a simplest possible log and the remainder when we do DNS wednesday.

**Comment by jjg** [comment]
I'm thinking about creating a general-purpose log sink for this.  This avoids the complexity of making it fit-in right with the CCR API, and also would allow us to use it to log things for simular applications (like Yahara plays, etc.).

Thoughts @prestonaustin ?

**Comment by prestonaustin** [comment]
Fine with me, gives client dev more latitude too.

**Comment by jjg** [comment]
I'll go that route then.  The interface will be very simple, accepting a POST request of some JSON data that I'll spec. here as soon as I can.  I'm not sure that I'll have a production version of this ready by first thing tomorrow, but I'll try.

**Comment by prestonaustin** [comment]
@jjg Much appreciated. Having the basic data logged is critical to beta as
those are deemed royalty-relevant streams and downloads.

**Comment by jjg** [comment]
Here's what I think we need to log in order to generate the reports described in the PDF:

* deal type code (stream, download, etc.)
* unique track identifier
* track title
* track primary artist
* label name
* price
* payable to SOCAN
* payable to CSI
* unique visitor id

I don't know if we need to log the "payable" stuff or if that can be inferred, if we can leave it out that's great.

There is also a lot of provisions in the PDF regarding "bundles".  It's not clear to me if this is something that pertains to this system (perhaps if we were zipping up tracks into downloads?).  In any event I left it out for now, but if you think we need it we can add those properties to the object accordingly.

Based on that, here's what I propose the client post to the logging server:

````
{
    "log_level": 0,
    "user_id": "",
    "event_type": "stream",
    "track_id": 1,
    "track_title": "A Track Name",
    "track_artist": "An Artist Name",
    "lable_name": "A Lable Name",
    "price": 0,
    "payable_to_socan": true,
    "payable_to_csi": true
}
````

I'm in the process of wrapping up the logging server now and I'll be deploying a production build asap.  The details about the logging server can be found here:

https://github.com/murfie/jlog

(feel free to pull that down for dev/debug, should run with the default config if you have a redis server running locally)

It's very flexible and open-ended, so changing the data logged above is not a big deal so long as we're capturing enough data to generate the required reports.

Let me know if you have questions and I'll post an update here as soon as I have the production server online.

**Comment by jjg** [comment]
*very* experimental production endpoint located here:

https://log.murfie.com/

Not a lot of exception handling yet, so make sure your requests are well-formed before sending them.  Minimally the "app" parameter should be specified, and the value should be: 4e392d7402d16170a352212f74ae2315

**Comment by acecarruthers** [comment]
@jjg bundles is their word for albums. Since we're not making full albums downloadable at once, we don't need to worry about bundles.

**Comment by jjg** [comment]
Sweet @acecarruthers :)

Also I fortified the production service a bit and fixed some bugs so it should be more stable now (and auto-recovering).  That said, be gentle :)

**Comment by mbrakken** [comment]
Given that people can stream without being logged in, is there a default I should use for user_id, or should the default be an empty string?

**Comment by prestonaustin** [comment]
Empty string in all cases I think. I don't want to report them. @jjg
@acecarruthers do we have to?


--
Preston Austin
preston.h.austin@gmail.com

**Comment by mbrakken** [comment]
gotcha. that makes it slight easier :)

**Comment by jjg** [comment]
Everything is optional from the engineering perspective.  The doc says it's a mandatory field, but if you're not reporting it, then there's no field.

**Comment by prestonaustin** [comment]
implement without, and I'll chat with EPL about that - seems odd that a
library would report individual user behavior on this, but I may have
missed something on Kelly's watch. I'll go read the faq ;)

**Comment by prestonaustin** [comment]
My read on EPL policy here: http://www.epl.ca/website-policy#confidentiality is that we _can't_ report this information. @acecarruthers have I got this right? Sorry for last minute question on this, I didn't realize there was a person identifier in the reporting format.

**Comment by acecarruthers** [comment]
@prestonaustin I'm looking through my notes on this because I believe this concern was addressed to my satisfaction back in January, but now I can't find the details.

**Comment by mbrakken** [comment]
i have logging or streaming tested and working. I'm assuming that for downloads, I just change `"event_type": "stream"` to `"event_type": "download"`. Correct?

**Comment by mbrakken** [comment]
Also, i'm logging when a track finishes playing or finishes downloading. Is that right, or should it be earlier in the life cycle (it's trivial to change).

**Comment by acecarruthers** [comment]
@mbrakken CSI says we owe them the royalty as soon as someone starts playing the track. It doesn't have to finish to be relevant to them. You are right about downloading though.

**Comment by prestonaustin** [comment]
@mbrakken correct on download. Yes log on completion, so we don't get
spurious logged activity because of stray clicks or quickly abandoned ones.
We can refine this later.

**Comment by mbrakken** [comment]
ok. i'll move up the playback log

**Comment by prestonaustin** [comment]
Or, we can refine it now, sorry @mbrakken

**Comment by jjg** [comment]
Correct on `event_type` @mbrakken.  There are other variations but I think for this application the only ones that are relevant are stream and download.

**Comment by acecarruthers** [comment]
@mbrakken, sorry I talked it over with Peter and we decided that it is fair to wait 6 seconds before we log anything for streaming. That will save us from spurious logged activity as @prestonaustin  said.

**Comment by acecarruthers** [comment]
@prestonaustin I am trying to get in contact with CSI to confirm what the user ID is meant to signify. You are correct that sending any personally identifying information is against our privacy policy. I don't think CSI wants personally identifying information though. I think they just want a sense of how much individuals use the service - to understand if we have power users who download a lot or whether downloads are spread evenly across all users - that kind of thing. I will get back to you as soon as I know more.

**Comment by mbrakken** [comment]
OK. Currently it logs right away. We'll need a small change to call it at
the 6 second mark, but that should be easy and will be implemented later.

**Comment by mbrakken** [comment]
FYI, i'm using as user ids a SHA1 hash of their card number (the server
does the same). I don't think it'd be easy to trace that back to a person
beyond our system.
